### ISSUE TITLE
Abort on bad websites

### ISSUE THREAD

**Issue by contolini** [cfpb/node-wcag#11]
If a request doesn't return `200`, tell the user they supplied a bad URL.

```
http.get('http://thisisnotalegitimatewebsite.foo').on('error', function() {
  console.log("You supplied an invalid URL.");
});
```

**Comment by zrrrzzt** [comment]
There's a module for that :-)

I always use [valid-url](https://www.npmjs.com/package/valid-url) when I need to ensure url validity.

``` javascript
var validUrl = require('valid-url')

if (opts.uri && !validUrl.isWebUri(opts.uri)) {
    return callback(new Error('You supplied an invalid URL.'), null);
}
```

**Comment by zrrrzzt** [comment]
...aaaaand I just realized a valid url still might be a bad/not working url

**Comment by zrrrzzt** [comment]
also important: URL might be https

**Comment by contolini** [comment]
Good call. I was going to try [node-ping](https://github.com/danielzzz/node-ping#tradition-calls) but it delegates to the OS's `ping` which fails if you prepend https:// (or even http://) to the URL.

**Comment by zrrrzzt** [comment]
Use the builtin url module [url](https://nodejs.org/docs/latest/api/url.html). The protocol-methods returns the protocol in lowercase. 
Or this nifty module [http-https](https://www.npmjs.com/package/http-https)
