### ISSUE TITLE
Split CLI as separate module

### ISSUE THREAD

**Issue by zrrrzzt** [cfpb/node-wcag#14]
I've always had one module containing both CLI and module. However, after reading [this](https://github.com/sindresorhus/ama/issues/17) I think it would be better to keep them apart.

``` sh
$ npm install wcag
```

Would install the module

``` sh
$ npm install wcag-cli -g
```

would install the CLI (much as it is today)

It would still be possible to enable use of wcag as CLI handle

``` sh
$ wcag <url> --key=<key>
```

**Comment by contolini** [comment]
Considering I still haven't [added the API to the readme](https://github.com/cfpb/node-wcag/issues/12), this makes sense to me. Couple questions:
- Would this repo become the API or the CLI?
- Should we remove `node-` from the repo name?

**Comment by zrrrzzt** [comment]
node- makes perfectly sense on GitHub but I would not use it on npm. 
So my idea is something like node-wcag (this repo) as the module and node-wcag-cli (wcag-cli on npm) as the new repo.

We haven't discussed versioning. I'm a big fan of semver at the moment so a 1.0.0 release of this repo/module would indicate breaking API changes and what we should do when we separate the CLI.
The CLI will depend on the module so minutes later we might release the wcag-cli 1.0.0.

I'm not in a hurry so we could start the split after we have solved the pending issues here.

**Comment by contolini** [comment]
:+1: to semver. Let's tie up this module's loose ends and follow your 1.0.0 plan.

**Comment by zrrrzzt** [comment]
If we still agree to do this: can you setup a node-wcag-cli repo? We can just copy this repo and take it from there.

**Comment by contolini** [comment]
@zrrrzzt On it.

**Comment by contolini** [comment]
Alright, I straight up copied it, including its history: https://github.com/cfpb/node-wcag-cli

**Comment by zrrrzzt** [comment]
:+1: Great. I'll start cleaning it up.
