### ISSUE TITLE
Parse multiple URLs at once

### ISSUE THREAD

**Issue by contolini** [cfpb/node-wcag#17]
i.e. Let the user do `wcag whatever.com anotherwebsite.com foo.com`.

I'm not even sure what the output would look like.

**Comment by zrrrzzt** [comment]
I prefer this module to check one URL at the time. 
It is quite trivial to create another module for looping and depend on this for the actual checking. Here's one example https://github.com/zrrrzzt/webquality-dashboard

Small focused modules ftw!

**Comment by contolini** [comment]
Works for me! I support any decision that makes my life easier.
