### ISSUE TITLE
Make it work as a module as well?

### ISSUE THREAD

**Issue by zrrrzzt** [cfpb/node-wcag#2]
Hi, I'm the developer of a similar solution https://github.com/zrrrzzt/wcag-validator. 
I would rather continue developing your version than my own, but I'll need it to work as a module in addition to a CLI version.
If you're interested I can do the necessary code changes myself and do a PR.

**Comment by contolini** [comment]
Absolutely! PRs are greatly appreciated. And thank you for writing wcag-validator, I referenced it when writing this CLI.

Currently, there is an undocumented API for index.js that is used by cli.js. After running `npm install wcag`, you can:

```
var wcag = require('wcag');

var opts = {
  uri: 'http://google.com',
  id: 'XXXXXXXXXXXX',
  guide: '508'
};

wcag(opts, function(err, report) {
  console.log(report);
});
```

This will print an object with a status, and arrays of errors and potential problems. For example:

```
{
    status: 'FAIL',
    errors: [{
        line: 38,
        column: 4941,
        message: 'Img element missing alt attribute.',
        solution: 'Add an alt attribute to your img element.'
    }],
    potentialProblems: [{
        line: 1,
        column: 175,
        message: 'Script may use color alone.',
        source: '(function(){window.google={kEI:\'BOBcVbQsgbCxBfvJgZAG\',kEXPI:\'18167,3700330,3700366,4003510,4 ...'
    }, {
        line: 1,
        column: 175,
        message: 'Script may cause screen flicker.',
        source: '(function(){window.google={kEI:\'BOBcVbQsgbCxBfvJgZAG\',kEXPI:\'18167,3700330,3700366,4003510,4 ...'
    }]
}
```

**Comment by zrrrzzt** [comment]
Nice. I'll try to implement this solution in some of my current reports. Fix whatever needed as I go.

I fell completely for your solution when I realised the use of localtunnel quite easily could be hacked to support static files as well :-)

**Comment by contolini** [comment]
I've found the localtunnel implementation to be a little buggy. It might be achecker.ca noticing a lot of requests from localtunnel.me and rate limiting the requests. Something to look out for.

Thanks for the interest and help! :smiley:
