### ISSUE TITLE
Appears to timeout sometimes

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/node-wcag#33]
Sometimes after repeatedly running the tests I get:

```
Error: Unexpected close tag
Line: 4
Column: 7
Char: >
```

**Comment by ashok-kumar** [comment]
Hey guys, any update on this ? 
Its not working for basic thing also. 

$ wcag wikipedia.org --id=<achecker id> --guide=508

Node version - v4.4.6
wcag - 0.2.2

Thanks in advance.

**Comment by contolini** [comment]
Hey @ashok-kumar thanks for pinging us about this. I'll look into this today.

**Comment by contolini** [comment]
Fixed and published as v0.3.0.

**Comment by ashok-kumar** [comment]
Hey @contolini thanks a lot for quick response. Just now i've tested with v0.3.0, it is working fine. Awesome!!!
