### ISSUE TITLE
localhost addresses ignore path and always test homepage

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/node-wcag#35]
To repeat:
1. Try `$ wcag localhost:8000 --id=<achecker id>`
2. Try `$ wcag localhost:8000/a/sub/path --id=<achecker id>`
3. Notice the errors will be identical because in both cases only the homepage is being checked.

**Comment by zrrrzzt** [comment]
As far as I can see the problem is cli.sj line 67.
According to [localtunnel docs](https://www.npmjs.com/package/localtunnel#localtunnel-port-opts-fn) tunnel.url returns the base url.
@contolini Should this part be moved out of cli.js and into index.js?

**Comment by anselmbradford** [comment]
@zrrrzzt Right you are. https://github.com/cfpb/node-wcag/blob/master/cli.js#L67 needs to be updated to:

``` js
validate(tunnel.url + url.parse( uri ).pathname, function() {
```

**Comment by contolini** [comment]
Daaaamn, nice sleuthing team!
